import { TBeverages } from "../Types";
import {
	Apple,
	BlackMilkTea,
	CocaCola,
	CoffeeShot,
	Focus, GoldenOolong,
	HersheysChocolateMilkshake,
	HersheysChocolateSyrup,
	Immunity, JasmineGreen,
	Mango,
	MatchaMilkTea,
	Sprite, Water
} from "../assets/images";

const Beverages: TBeverages = [
	{
		name: "CocaCola",
		description: "Such a good drink, should try it :)",
		price: 1.35,
		quantityAvailable: 21,
		tags: ["Carbonated Drinks", "Cool Drinks"],
		imgSrc: CocaCola,
		imgAlt: ""
	},
	{
		name: "Sprite",
		description: "Meh kinda drink, replacement when coke is available",
		price: 1.05,
		quantityAvailable: 17,
		tags: ["Carbonated Drinks", "Cool Drinks"],
		imgSrc: Sprite,
		imgAlt: ""
	},
	{
		name: "Energy + Focus",
		description: "Matcha and L-theanine partner with ginseng for an empowering, focused blend.",
		price: 35.99,
		quantityAvailable: 3,
		tags: ["Energy Drinks", "Healthy"],
		imgSrc: Focus,
		imgAlt: "",
	},
	{
		name: "Energy + Immunity",
		description: "Matcha and L-theanine partner with ginseng for an empowering, focused blend.",
		price: 35.99,
		quantityAvailable: 3,
		tags: ["Energy Drinks", "Healthy"],
		imgSrc: Immunity,
		imgAlt: "",
	},
	{
		name: "Apple Juice",
		description: "Packed with benefits of vitamins, calcium, potassium and magnesium, the fruit and its juice give out adequate health punch. Full of pectin and fiber, Apple juice helps boost energy.",
		price: 12.5,
		quantityAvailable: 3,
		tags: ["Juices", "Healthy", "Cool Drinks"],
		imgSrc: Apple,
		imgAlt: "",
	},
	{
		name: "Mango Juice",
		description: "Enriched in protein, fiber, vitamins, iron and other essential minerals, mangoes add immense value to anyone's diet, especially kids.",
		price: 22.5,
		quantityAvailable: 9,
		tags: ["Juices", "Healthy", "Cool Drinks"],
		imgSrc: Mango,
		imgAlt: "",
	},
	{
		name: "Black Milk Tea",
		description: "The perfect café experience in a bottle! We put our tea expertise to work by balancing the robust flavor black tea with a sweet creamy taste. Enjoy it any time of the day without the fuss of being a barista or brewing your own tea. ",
		price: 23.50,
		quantityAvailable: 3,
		tags: ["Milk", "Tea"],
		imgSrc: BlackMilkTea,
		imgAlt: "",
	},
	{
		name: "Matcha Milk Tea",
		description: "A true Japanese favorite! We put our tea expertise to work by balancing the flavors of matcha and green tea with a sweet creamy taste. Enjoy it any time of the day without the fuss of being a barista or brewing your own tea.",
		price: 35.99,
		quantityAvailable: 5,
		tags: ["Milk", "Tea"],
		imgSrc: MatchaMilkTea,
		imgAlt: "",
	},
	{
		name: "Coffee Shot",
		description: "The Jay Street Coffee Shot is inspired by the cobblestone streets of our Brooklyn home office. This bold-tasting coffee shot will get you up and going anytime you need a natural energy boost. Unsweetened with 150mg of caffeine per bottle.",
		price: 35,
		quantityAvailable: 4,
		tags: ["Coffee"],
		imgSrc: CoffeeShot,
		imgAlt: "",
	},
	{
		name: "Golden Oolong",
		description: "ITO EN's Golden Oolong Tea is one of Japan's best selling Oolong Teas. The tea leaves used for this Golden Oolong are flowery, fragrant \"Golden Cinnamon\" and hearty and ripe \"Iron Goddess\". Oolong tea is semi oxidized, making it unique from green and black teas.",
		price: 23.50,
		quantityAvailable: 6,
		tags: ["Tea"],
		imgSrc: GoldenOolong,
		imgAlt: "",
	},
	{
		name: "Jasmine Green",
		description: "We use jasmine flowers that have been picked when the blossoms are at the peak of their fragrance.",
		price: 23.50,
		quantityAvailable: 2,
		tags: ["Tea"],
		imgSrc: JasmineGreen,
		imgAlt: "",
	},
	{
		name: "Water",
		description: "Just drink it.",
		price: 20.00,
		quantityAvailable: 10,
		tags: ["Water"],
		imgSrc: Water,
		imgAlt: "",
	},
	{
		name: "Hershey's Milkshake",
		description: "Creamy. Classic. Delicious. You can call HERSHEY'S Chocolate Milkshake recipe by quite a few names, and while you’re at it, you can add quick, easy and popular to the list. In just five minutes and with three simple ingredients — cold milk, HERSHEY’S syrup and vanilla or chocolate ice cream — you can make easy homemade milkshakes for two. You can even choose your favorite milkshake consistency by blending until it flows just right. The ingredients are in your kitchen calling your name right now. Just blend, pour, garnish if desired and enjoy with a loved one.",
		price: 30.00,
		quantityAvailable: 10,
		tags: ["Chocolate", "Healthy", "Cool Drinks", "Milk"],
		imgSrc: HersheysChocolateMilkshake,
		imgAlt: "",
	},
	{
		name: "Hershey's Syrup",
		description: "Hershey's syrups have been the stronghold of the Hershey's brand for many years now. One dose of rich Hershey's syrup is all it takes to add that zing to every second glass of milk. Hershey's Strawberry Syrup is a great companion for your milkshakes, ice creams or desserts. Made using fresh strawberries, this ingredient adds an extra colour and flavour to your sweet course. Its sweetness and vibrant red colour is simply amazing. Versatile in taste and use, it is available in a pet jar with an easy to flip cap.",
		price: 120.00,
		quantityAvailable: 2,
		tags: ["Chocolate"],
		imgSrc: HersheysChocolateSyrup,
		imgAlt: "",
	},
];

export default Beverages;